// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPHXwRErRkqD6i2h7qlv3nPjDt3vMTYI',
    appId: '1:86334786269:web:fbd191bb177b2515296934',
    messagingSenderId: '86334786269',
    projectId: 'find-52c84',
    authDomain: 'find-52c84.firebaseapp.com',
    storageBucket: 'find-52c84.firebasestorage.app',
    measurementId: 'G-2FDMJJBMMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQ4kqdNu-wOSWLXjIwysm-6Q1KXQooNU',
    appId: '1:86334786269:android:7e301a2542d36758296934',
    messagingSenderId: '86334786269',
    projectId: 'find-52c84',
    storageBucket: 'find-52c84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2DjInYNrzhF0pZ7tG0tQxTmyboXX0a0',
    appId: '1:86334786269:ios:cde0821f7ac6e32e296934',
    messagingSenderId: '86334786269',
    projectId: 'find-52c84',
    storageBucket: 'find-52c84.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2DjInYNrzhF0pZ7tG0tQxTmyboXX0a0',
    appId: '1:86334786269:ios:cde0821f7ac6e32e296934',
    messagingSenderId: '86334786269',
    projectId: 'find-52c84',
    storageBucket: 'find-52c84.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXPHXwRErRkqD6i2h7qlv3nPjDt3vMTYI',
    appId: '1:86334786269:web:66c0dccc3f297551296934',
    messagingSenderId: '86334786269',
    projectId: 'find-52c84',
    authDomain: 'find-52c84.firebaseapp.com',
    storageBucket: 'find-52c84.firebasestorage.app',
    measurementId: 'G-BQ03HTWGV5',
  );

}